version: 2
formats: []

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html

build:
  os: ubuntu-20.04
  tools:
    python:
      version: "3.13.0"
      install:
        - pip
        - setuptools
        - wheel
        - docs
        - sphinx
        - sphinx-rtd-theme
        - requirements: requirements.txt
  commands:
    - pip install -U pip
    - pip install -e .[docs]
    - sphinx-build -W -b html docs docs/_build/html