version: 2
formats: []

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html

build:
  os: ubuntu-20.04
  apt_packages:
    - python3-sphinx
  tools:
    python: "3.13"
  commands:
    - pip install -U pip
    - pip install -e .[docs]
    - pip install -r docs/requirements.txt
    - python -m sphinx.cmd.build -W -b html docs $READTHEDOCS_OUTPUT/html

python:
  install:
    - requirements: docs/requirements.txt